### PR TITLE
Fix QA Environment GCP Deployment

### PR DESCRIPTION
**Pull request by opauloh**
### Summary

This fixes https://github.com/elastic/kibana/issues/169098

This PR updates the package version to the most up-to-date and also sends the required parameter `gcp.account_type`

### CODE REVIEW

**Comment by opauloh** [comment]
> WDYT about merging this to unblock the QA cycle and opening a follow-up ticket to conditionally change the json depending on the version?

Agree with that, also bringing up the following discussion here:

As we might face this issue on adding new fields, what if we start adopting the branch versioning for creating older stack deployments? For example, to create an 8.10 environment we set the option of running a workflow from the 8.10 branch so it uses versioned code.

I know it wouldn't deploy GCP in that way for 8.10, as it was added in the 8.11 branch code, but I think standardizing this format might be a good idea for solving the issues with older stacks deployment

image (7)
it was working on 8.10

**Comment by orestisfl** [comment]
> As we might face this issue on adding new fields, what if we start adopting the branch versioning for creating older stack deployments? For example, to create an 8.10 environment we set the option of running a workflow from the 8.10 branch so it uses versioned code.

Agreed, adding the backport label here to apply the changes also to the 8.11 branch.

**Review by orestisfl — APPROVED** [review]

**Comment by opauloh** [comment]
a Codeowner can feel free to merge this PR, as I don't have permission to merge

**Comment by orestisfl** [comment]
Something is wrong with your branch:

```
remote: error: GH006: Protected branch update failed for refs/heads/opauloh-patch-1.
remote: error: This branch must not contain merge commits. Changes must be made through a pull request. Required status check "CLA" is expected.
To https://github.com/elastic/cloudbeat
 ! [remote rejected]   opauloh-patch-1 -> opauloh-patch-1 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/elastic/cloudbeat'
```

Can you please rebase with `main` so that we can merge?

**Comment by orestisfl** [comment]
@oren-zohar The PR was not made from a fork so we now can't update the PR as the branch is protected for some reason. Can you please merge?

```
remote: error: GH006: Protected branch update failed for refs/heads/opauloh-patch-1.
remote: error: This branch must not contain merge commits. Changes must be made through a pull request. Required status check "CLA" is expected.
To https://github.com/elastic/cloudbeat
 ! [remote rejected]   opauloh-patch-1 -> opauloh-patch-1 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/elastic/cloudbeat
```

**Review by oren-zohar — APPROVED** [review]

**Comment by oren-zohar** [comment]
> The PR was not made from a fork so we now can't update the PR as the branch is protected for some reason. Can you please merge?

@orestisfl worked for me from the UI, I wonder why

**Comment by orestisfl** [comment]
> > The PR was not made from a fork so we now can't update the PR as the branch is protected for some reason. Can you please merge?
> 
> @orestisfl worked for me from the UI, I wonder why

Because you probably have more permissions?

**Pull request merged**
