### PR TITLE
action: bump-golang with service account

### PR DESCRIPTION
**Pull request by v1v**
### Summary of your changes

Use service account for creating PRs with the bump update.

### Tasks

I cannot create the GitHub secrets, but it's required the below secrets for this project:

```bash
gh secret set VAULT_SECRET_ID --body "$(vault read -field vault_secret_id secret/jcasc/localhost/apm-ci)"
gh secret set VAULT_ROLE_ID --body "$(vault read -field vault_role_id secret/jcasc/localhost/apm-ci)"
gh secret set VAULT_ADDR --body "https://secrets.elastic.co:8200"
```

### CODE REVIEW

**Review by gurevichdmitry — CHANGES_REQUESTED** [review]
@v1v pre-commit hooks action is [failed](https://github.com/elastic/cloudbeat/actions/runs/4185052506/jobs/7251552237), please check. I don't have access to GH secrets, @oren-zohar can you please assist?

**Comment by oren-zohar** [comment]
> I cannot create the GitHub secrets, but it's required the below secrets for this project:
> 
> ```shell
> gh secret set VAULT_SECRET_ID --body "$(vault read -field vault_secret_id secret/jcasc/localhost/apm-ci)"
> gh secret set VAULT_ROLE_ID --body "$(vault read -field vault_role_id secret/jcasc/localhost/apm-ci)"
> gh secret set VAULT_ADDR --body "https://secrets.elastic.co:8200"
> ```

@v1v I'm not sure how to access them, should I have access to these secrets?

**Comment by v1v** [comment]
> I'm not sure how to access them, should I have access to these secrets?

I think so, if you have configured the access to Vault, then you most likely have access. Otherwise you can grant me admin access temporarily so I can enable those gh secrets

**Review by oren-zohar — APPROVED** [review]
I've added the relevant secretes to the repo, it should work now

**Review by gurevichdmitry — APPROVED** [review]
@v1v - approved.

**Pull request merged**
