### PR TITLE
Update CNVM findings schema

### PR DESCRIPTION
**Pull request by uri-weisman**
### Summary of your changes
1. class -> vulnerability.class
2. target -> package.path
3. type -> package.type
4. Move vulnerability.package to be directly under package as defined in the technical index and in [ECS](https://www.elastic.co/guide/en/ecs/8.7/ecs-package.html).
5. Upgrade elastic-package binary to the latest.

### Related Issues
- Fixes: https://github.com/elastic/cloudbeat/issues/897

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

Screenshot 2023-05-01 at 13 45 13
Screenshot 2023-05-01 at 13 45 35

### CODE REVIEW

**Review by amirbenun — APPROVED** [review]
1. Do we want to backport?
2. In https://github.com/elastic/cloudbeat/issues/897 there is also `cluster_id` do we want to change it on a different PR?

**Comment by oren-zohar** [comment]
@kfirpeled do we want to backport this?

**Comment by uri-weisman** [comment]
> 2. In [Move non-ECS fields from root level event #897](https://github.com/elastic/cloudbeat/issues/897) there is also `cluster_id` do we want to change it on a different PR?

@amirbenun - Feels like it does not relate to the CNVM flow as we don't send this field.
I'll open a follow-up task for removing the `cluster_id` field (it has already an alternative - `orchestrator.cluster.id`), it will be a bit more complicated as it is a breaking change.

**Comment by kfirpeled** [comment]
> @kfirpeled do we want to backport this?

Yes, looking at the current implementation: 
- having package both in the root level and under vulnerability
- moving `type`, `target` and `class` from the root level

We agree to backport that to 8.8

cc: @uri-weisman

**Pull request merged**
