### PR TITLE
[Terraform] Deploy CSPM AWS agent using docker

### PR DESCRIPTION
**Pull request by kfirpeled**
### Summary of your changes

In this PR we use the same ec2 machine that was set up for kspm vanilla, to run CSPM AWS agent using docker

This PR depends on https://github.com/elastic/cloudbeat/pull/966

### How to test it

Run the full step-by-step instructions: https://github.com/elastic/cloudbeat/tree/main/deploy/cloud

For your convenience, you can contact it with a single command (change DEPLOYMENT_NAME): 

```
export TF_VAR_deployment_name=<DEPLOYMENT_NAME>
terraform apply --auto-approve -target "module.ec_deployment" -target "null_resource.rules" -target "null_resource.store_local_dashboard" -target "module.eks" \
   && terraform apply --auto-approve -target "module.aws_ec2_with_agent" \
   && terraform apply --auto-approve -target "module.apps" \ 
   && terraform apply --auto-approve -target "module.api" -target "module.iam_eks_role" \
   && terraform apply --auto-approve
```

### Screenshot/Data

Screenshot 2023-05-11 at 22 09 23

Screenshot 2023-05-11 at 22 10 27

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary README/documentation (if appropriate)

### CODE REVIEW

**Comment by kfirpeled** [comment]
I haven't added the necessary README/documentation yet

**Comment by kfirpeled** [comment]
@oren-zohar current I set up CSPM with the same EKS role, which obviously doesn't work.
What do you suggest to do instead?

**Comment by gurevichdmitry** [comment]
@kfirpeled, I'm trying to provision the deployment using the following command:
```bash
terraform apply --auto-approve \
   -var="stack_version=8.7.2-SNAPSHOT" \
   -var="agent_docker_image_override=docker.elastic.co/beats/elastic-agent:8.7.2-SNAPSHOT" \
   -var="ess_region=gcp-us-west2"
```
The deployment fails on the following:
```
╷
│ Error: uri must be set to construct an API client
│ 
│   with provider["registry.terraform.io/mastercard/restapi"],
│   on main.tf line 90, in provider "restapi":
│   90: provider "restapi" {
│ 
╵
```

**Comment by kfirpeled** [comment]
> @kfirpeled, I'm trying to provision the deployment using the following command:
> 
> ```shell
> terraform apply --auto-approve \
>    -var="stack_version=8.7.2-SNAPSHOT" \
>    -var="agent_docker_image_override=docker.elastic.co/beats/elastic-agent:8.7.2-SNAPSHOT" \
>    -var="ess_region=gcp-us-west2"
> ```
> 
> The deployment fails on the following:
> 
> ```
> ╷
> │ Error: uri must be set to construct an API client
> │ 
> │   with provider["registry.terraform.io/mastercard/restapi"],
> │   on main.tf line 90, in provider "restapi":
> │   90: provider "restapi" {
> │ 
> ╵
> ```

@gurevichdmitry can you check if you set `EC_API_KEY`?

**Comment by kfirpeled** [comment]
@olegsu I've updated the readme

**Comment by gurevichdmitry** [comment]
> EC_API_KEY

@kfirpeled, The environment variable EC_API_KEY and the Terraform variable TF_VAR_ec_api_key are both configured. I know that only one is required, but I have checked both cases and encountered the same error.

**Comment by kfirpeled** [comment]
@gurevichdmitry I started now another test from scratch and it works

Screenshot 2023-06-08 at 13 38 06

Still creating the EC2 instance so no agents at this moment
I used version `8.8.0` without agent docker override

Can you confirm that you start with a clean terraform state? And what is your terraform version?

**Pull request merged**
