### PR TITLE
Add csp task template

### PR DESCRIPTION
**Pull request by eyalkraft**

### CODE REVIEW

**Review by DaveSys911 — APPROVED** [review]
Lgtm

**Comment by oren-zohar** [comment]
I would suggest marking some parts as hidden, like that:
```
<!-- This is hidden unless you edit. -->
```

People will probably ignore some parts of the template but won't delete them, so we will see a lot of text from the template that it not relevant :( we can just mark most of it as hidden in the first place

**Comment by eyalkraft** [comment]
@oren-zohar which parts?

**Comment by oren-zohar** [comment]
you do it for each part, or just the parts you think users will probably are going to ignore the most

**Pull request merged**
