### PR TITLE
attempt to fix ga hermit cache

### PR DESCRIPTION
**Pull request by moukoublen**
### Related Issues

Fixes: https://github.com/elastic/cloudbeat/issues/1175

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary README/documentation (if appropriate)

#### Introducing a new rule?

- [ ] Generate rule metadata using [this script](https://github.com/elastic/cloudbeat/tree/main/security-policies/dev#generate-rules-metadata)
- [ ] Add relevant unit tests
- [ ] Generate relevant rule templates using [this script](https://github.com/elastic/cloudbeat/tree/main/security-policies/dev#generate-rule-templates), and open a PR in [elastic/packages/cloud_security_posture](https://github.com/elastic/integrations/tree/main/packages/cloud_security_posture)

### CODE REVIEW

**Review by orestisfl — COMMENTED** [review]
What about https://github.com/cashapp/activate-hermit that has a cache option?

**Comment by moukoublen** [comment]
@orestisfl that was my first thought but we need some extra directories in cache that are not included in `https://github.com/cashapp/activate-hermit`. 

We need (so far):
```
          ~/.cache/hermit/pkg
          ./.hermit
          ~/.cache/go-build
          ~/go/pkg/
          ~/.cache/pre-commit
```

This is still draft. I am stiil thinking about the optimal way to separate the caches in order not to get overwritten (because cloudbeat has a lot workflows that run in parallel using the same -or not- cache).

**Comment by orestisfl** [comment]
Great, thanks. How are we going to handle the case where different items are cached depending on the pipeline? For example, opa pipelines will just initialize `opa` while go tests will initialize ~/go as well.

**Comment by moukoublen** [comment]
This is what I meant when I wrote that I am still thinking about the optimal way to separate the caches in order not to get overwritten. Different pipelines run in parallel and might initialize different parts of "cache". (Hermit install at the beginning is the easy part and already implemented. The difficult part are python envs, go pks and pre-commit cache). 

This is still wip

**Comment by moukoublen** [comment]
closed due to this: https://github.com/elastic/cloudbeat/pull/2000

**Pull request closed without merging**
