### PR TITLE
automate golang version bump

### PR DESCRIPTION
**Pull request by v1v**
In addition I configured the GitHub actions to read the `.go-version` so the version is not anymore hardcoded.

A similar approach was done in Beats, see https://github.com/elastic/beats/blob/3668fd6909afa261edc563d710a12fa879d5d588/.github/workflows/check-metricbeat.yml#L18-L22

This approach will help to bump the Golang version automatically similarly done with Beats and other projects, see https://github.com/elastic/beats/pull/32574

### CODE REVIEW

**Review by DaveSys911 — APPROVED** [review]
Lgtm
@v1v The plan is to automatically align other repos go versions with beats/lib-beat right?

**Comment by v1v** [comment]
> @v1v The plan is to automatically align other repos go versions with beats/lib-beat right?

That's correct. The existing automation behaves similar to dependabot in terms of bumping the go version by using a Pull Request.

If needed, you can even diverge from the existing default go1.18 version if `go1.19` is required to be used in the future. So far, it will use the same approach as done for `Beats`/`ElasticAgent`/...

**Comment by v1v** [comment]
https://github.com/elastic/cloudbeat/runs/8109273794?check_suite_focus=true#step:4:36 failed , no idea the reason.

Let me know if something else is missing

**Comment by DaveSys911** [comment]
> https://github.com/elastic/cloudbeat/runs/8109273794?check_suite_focus=true#step:4:36 failed , no idea the reason.
> 
> Let me know if something else is missing

Re-running ci and updating from main.

**Comment by v1v** [comment]
> Re-running ci and updating from main.

CI failures were genuine, I somehow missed the `golint` used the GO_VERSION, hence https://github.com/elastic/cloudbeat/pull/368/commits/71d02b59cf67805e28e05f4f4c61ae113c575418 and https://github.com/elastic/cloudbeat/pull/368/commits/d7507bd8438a1182c46d0c7e65b2c93bd5eebf3c should fix the CI failures

Sorry for the back and forth!

**Comment by v1v** [comment]
@DaveSys911 , any feeback? 🙏

**Comment by DaveSys911** [comment]
> @DaveSys911 , any feeback? 🙏

LGTM, updating branch and setting to auto-merge.

**Pull request merged**
