### PR TITLE
Add tf run agent on eks

### PR DESCRIPTION
**Pull request by eyalkraft**
**What does this PR do?**

What the Terraform script currently does is:
1. Deploys an Elastic cloud environment (supports configuring specific version)
2. Deploys an EKS cluster including required identity provider and roles
3. Creates the Daily environment Dashboard and rules
4. Creates an agent policy with our EKS Benchmark integration installed on it
5. Deploys a fleet-managed agent that authenticates to AWS using assume role on the EKS cluster

Tech debts:
1. Creating a "vanilla" non managed k8s cluster and deploying the agent on it. The tf script will have to:
    a. Provision (two? unless we use kind) ec2 machines to be the nodes
    b. Install K8s (using `kubeadm`?)
    c. deploy the agent
6. Currently the script assumes the existence of the IAM policies
    ```
    Developers_eks = "arn:aws:iam::704479110758:policy/Developers_eks"
    EKS_ReadAccess = "arn:aws:iam::704479110758:policy/EKS_ReadAccess"
    ```
    A more proper way would be to have the tf script provision the required policy itself.
7. Improving the tf script (moving things from main to modules, unifying the way we create the dashboard & the rules with `module.api`)
8. Reducing the number of steps required to deploy (currently 3)

**Related Issues**

- closes https://github.com/elastic/security-team/issues/5551

**Checklist**
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary README/documentation (if appropriate)

### CODE REVIEW

**Comment by eyalkraft** [comment]
Everything but assuming the role works.
```
{
    "log.level": "error",
    "@timestamp": "2022-12-15T14:31:43.545Z",
    "log.logger": "starter",
    "log.origin": {
        "file.name": "launcher/launcher.go",
        "file.line": 107
    },
    "message": "Could not run Beater: could not create beater: could not retrieve user identity for ECR fetcher: operation error STS: GetCallerIdentity, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: b93a9a07-78f3-4830-8b96-07301a54af85, api error AccessDenied: User: arn:aws:sts::704479110758:assumed-role/cloudbeat-tf-BNu-2-eks-node-group-20221215135528997200000009/i-0ac30f6f47c2d1ddb is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::704479110758:role/cloudbeat-tf-BNu",
    "service.name": "cloudbeat",
    "ecs.version": "1.6.0"
}
```
This causes cloudbeat to crash.

**Comment by eyalkraft** [comment]
Everything works.

**Comment by eyalkraft** [comment]
Tech debts:
1. Less steps?
2. Prettier terraform?

**Comment by eyalkraft** [comment]
@gurevichdmitry README improved

**Review by gurevichdmitry — APPROVED** [review]
@eyalkraft, great job! LGTM

**Pull request merged**
