### PR TITLE
Update Beats dependency and elastic-agent-client

### PR DESCRIPTION
**Pull request by rdner**
### Summary of your changes

This allows to support setting GOMAXPROCS via the control protocole. For details see:

* https://github.com/elastic/elastic-agent-client/pull/83
* https://github.com/elastic/beats/pull/36301
* https://github.com/elastic/elastic-agent/pull/3179

### CODE REVIEW

**Comment by amitkanfer** [comment]
@oren-zohar

**Comment by cmacknz** [comment]
Looks like Oren beat you to it: https://github.com/elastic/cloudbeat/pull/1228

**Comment by amitkanfer** [comment]
@oren-zohar beats everyone

**Comment by rdner** [comment]
@cmacknz @amitkanfer @oren-zohar I see. But https://github.com/elastic/cloudbeat/pull/1228 does not update the libbeat version, this PR is more complete, I think.

**Review by oren-zohar — APPROVED** [review]
Thanks :heart:

**Pull request merged**
