### PR TITLE
[Terraform] Allow agent docker image override

### PR DESCRIPTION
**Pull request by kfirpeled**
### Summary of your changes

Introduced `agent_docker_image_override` variable to override the agent image
Useful for testing purposes when current version hasn't been released yet

### Screenshot/Data

**Naming EC2 instances (eks nodes + ec2 for vanilla testing):** 
Screenshot 2023-05-11 at 15 36 40

### Checklist
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary README/documentation (if appropriate)

### CODE REVIEW

**Comment by oren-zohar** [comment]
Do we have a doc for the workflow you edited? can we add it there?

**Review by gurevichdmitry — CHANGES_REQUESTED** [review]
@kfirpeled great work!
There are some comments regarding the pull request.
To ensure smooth deployment and address the errors like missing restapi uri, please provide the instructions how to deploy. This will allow to thoroughly test and validate your improvements.
nit: Regarding the idea of dividing the API for EKS and Vanilla, it is indeed a great approach. However, there is some code duplication related to agent_policy and enrollment_token. If changes occur in the fleet api, refactoring will be required. To address this, we can consider introducing a new module called "fleet" that encompasses all the common functionality required by both api.eks and api.vanilla. This will allow the APIs to depend on the "fleet" module, reducing code duplication and improving maintainability.

**Comment by kfirpeled** [comment]
I've added examples in the docs

> nit: Regarding the idea of dividing the API for EKS and Vanilla, it is indeed a great approach. However, there is some code duplication related to agent_policy and enrollment_token. If changes occur in the fleet api, refactoring will be required. To address this, we can consider introducing a new module called "fleet" that encompasses all the common functionality required by both api.eks and api.vanilla. This will allow the APIs to depend on the "fleet" module, reducing code duplication and improving maintainability.

I'm not sure I fully understood what you suggest to refactor, and how. So if you can give an example and point me to exactly what you ask it would help me understand your point

**Comment by gurevichdmitry** [comment]
> I've added examples in the docs
> 
> > nit: Regarding the idea of dividing the API for EKS and Vanilla, it is indeed a great approach. However, there is some code duplication related to agent_policy and enrollment_token. If changes occur in the fleet api, refactoring will be required. To address this, we can consider introducing a new module called "fleet" that encompasses all the common functionality required by both api.eks and api.vanilla. This will allow the APIs to depend on the "fleet" module, reducing code duplication and improving maintainability.
> 
> I'm not sure I fully understood what you suggest to refactor, and how. So if you can give an example and point me to exactly what you ask it would help me understand your point

For example, if we have the same `agent_policy` resource defined in both the `eks` and `vanilla` modules, we can consider creating a separate module called `fleet_api`. This module would contain the resource definition for `agent_policy` and expose the `policy_data` as a configurable variable.

`fleet/main.tf`
```terraform
resource "restapi_object" "agent_policy" {
  provider     = restapi
  path         = "/api/fleet/agent_policies"
  id_attribute = "item/id"
  data         = var.policy_data

  # destroy does not work :(
  destroy_path   = "/api/fleet/agent_policies/delete"
  destroy_method = "POST"
  destroy_data   = <<EOF
{
  "agentPolicyId" : "{id}"
}
EOF
}

variable "policy_data" {
    
    description = "json data"
    type = string
}

output "agent_policy_id" {
    value = rest_api.agent_policy.id
}
```
In `vanilla/main.tf`:

```
module "fleet_api" {

    source = "../fleet"

    policy_data = file("data/agent_policy_vanilla.json")

    # other configuration
}
```

In `eks/main.tf`:

```
module "fleet_api" {
    source = "../fleet"

    policy_data = file("data/agent_policy_eks.json")
    
    # other configuration
}
```

**Comment by gurevichdmitry** [comment]
> > For example, if we have the same agent_policy resource defined in both the eks and vanilla modules, we can consider creating a separate module called fleet_api. This module would contain the resource definition for agent_policy and expose the policy_data as a configurable variable.
> 
> we don't define the same agent policy in terraform. We have a different agent policy for each deployment. In that case, is there any other refactoring you would suggest?

You are correct. Although the policies are different, both the vanilla and eks modules share the same code to interact with the API resource.

**Review by gurevichdmitry — APPROVED** [review]
approved

**Pull request merged**
