### PR TITLE
disable stderr logging by default

### PR DESCRIPTION
**Pull request by oren-zohar**
1. disable logging to the stderr by default
2. ???
3. profit
___
- Related: https://github.com/elastic/security-team/issues/4168
- Fixes: https://github.com/elastic/cloudbeat/issues/231

### CODE REVIEW

**Review by DaveSys911 — APPROVED** [review]
Not sure, what will happen here, since the file output is set to true- good idea to check it doesn't  fill up the space and crash the container.
image

**Comment by DaveSys911** [comment]
Why stderr https://github.com/elastic/beats/pull/19848
@oren-zohar

**Comment by amitkanfer** [comment]
🚢 it

**Comment by oren-zohar** [comment]
@amitkanfer integration tests are flaky/broken 😭

**Comment by amitkanfer** [comment]
> @amitkanfer integration tests are flaky/broken 😭

good, let's fix them :)

**Pull request merged**
