### PR TITLE
Add message to our findings

### PR DESCRIPTION
**Pull request by eyalkraft**
closes https://github.com/elastic/security-team/issues/3786

Before:
Screen Shot 2022-07-13 at 18 13 34

Screen Shot 2022-07-13 at 18 14 18

After:
Screen Shot 2022-07-13 at 20 27 30

### CODE REVIEW

**Comment by amitkanfer** [comment]
👑

**Review by uri-weisman — APPROVED** [review]
NIce! I guess that we need to update the findings mapping as well.

**Comment by oren-zohar** [comment]
Does it close this?
- https://github.com/elastic/cloudbeat/issues/238

**Comment by eyalkraft** [comment]
@oren-zohar It does for findings but I'm afraid maybe there are some other log messages cloudbeat produces the don't have a message field? wdyt?

**Comment by oren-zohar** [comment]
I'll keep an eye on it for the next couple of days, if we don't see it anymore I'll close it. We can always re-open it.

**Pull request merged**
