### PR TITLE
Move strings.Dereference to ptrs.Deref

### PR DESCRIPTION
**Pull request by romulets**
### Summary of your changes

In a previous PR the `ptrs.Deref` was introduced, which is a generic version of the string specific `strings.Dereference`. This PR refactors the usage of strings to the generic ptrs

### Checklist
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by moukoublen** [comment]
Perhaps the package can be named `pointers` (like `strings`, `slices` or `maps`) instead of `ptrs`. 

(Totally optional though)

**Comment by romulets** [comment]
Fair point, done @moukoublen

**Comment by orestisfl** [comment]
Unfortunately, this now loses the typing information as it's not clear immediately that the argument is a string

**Comment by romulets** [comment]
What do you mean with typing information? @orestisfl

**Comment by moukoublen** [comment]
@orestisfl I think an alternative (since its generic) could be to write it like this if you want to:

```golang
s := pointers.Deref([string](ptr)
```

**Comment by orestisfl** [comment]
Maybe just name it `pointers.ToString()`?

**Review by orestisfl — APPROVED** [review]

**Comment by romulets** [comment]
@orestisfl and I chatted and there was a miscommunication regarding the behaviour of `pointers.Deref`. He thought it was for string only, while it is for any type. We agreed the code is good enough as it's

**Pull request merged**
