### PR TITLE
fixing the common.yml.tmpl

### PR DESCRIPTION
**Pull request by ofiriro3**
- fixes : https://github.com/elastic/security-team/issues/3041

### CODE REVIEW

**Comment by eyalkraft** [comment]
currently looks like a local problem

**Comment by eyalkraft** [comment]
The problem is that our build process (specifically `make PackageAgent`) changes the files:
```
	modified:   cloudbeat.reference.yml
	modified:   cloudbeat.yml
	modified:   docs/fields.asciidoc
```

Are you familiar with this behavior?

**Comment by eyalkraft** [comment]
The problem is probably that I wasn't running with this change :)

**Comment by ofiriro3** [comment]
@eyalkraft updated us that this fix solves his problem, he just had to solve something on his local machine

**Pull request merged**
